apiVersion: v1
kind: PersistentVolume
metadata:
  name: tekton-pipeline-run-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: "/tmp/data"
