apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.service.name }}-service
  labels:
    app: webapp
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
   - protocol: TCP
     port: {{ .Values.webapp.port }}
     nodePort: {{ .Values.webapp.nodePort }}
